# Generated by Django 5.1.3 on 2024-12-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_product_quantity_purchase_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="max_quantity",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
