# Generated by Django 5.1.3 on 2024-12-05 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_purchase_order_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="order_amount",
        ),
    ]
